version: "3"
services:
  web:
    build: .
    volumes:
      - .:/api
    ports:
      - 8000:8000
    environment:
      ENV: development

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: selfmanagement
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  # :: Optional pgadmin interface ::
  #    - Log in with pgadmin4@pgadmin.org and password admin
  #    - the default database is either POSTGRES_DB or POSTGRES_USER 
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
